apiVersion: batch/v1
kind: CronJob
metadata:
  name: ec2-power-scheduler
  namespace: ec2-power-scheduler
spec:
  suspend: true  # Temporarily disable the cronjob
  schedule: "*/30 * * * *"  # Every 30 minutes (K8s minimum interval)
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3  # Keep 3 successful jobs (default)
  failedJobsHistoryLimit: 1      # Keep only 1 failed job
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ec2-power-scheduler-sa
          containers:
          - name: scheduler
            image: cr.aops.tools/aops-docker-repo/ec2-power-scheduler:latest
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
          restartPolicy: OnFailure 