apiVersion: v1
kind: Secret
metadata:
  name: slack-bot-token
  namespace: ec2-power-scheduler
type: Opaque
data:
  # The token value should be base64 encoded
  # You can encode it with: echo -n "xoxb-your-token-here" | base64
  token: <base64-encoded-slack-bot-token>