name: CI

on:
  workflow_dispatch:

env:
  REGISTRY: cr.aops.tools/aops-docker-repo
  IMAGE_NAME: ec2-power-scheduler
  K8S_NAMESPACE: ec2-power-scheduler
  K8S_RESOURCE_TYPE: cronjob
  K8S_RESOURCE_NAME: ec2-power-scheduler
  K8S_CONTAINER_NAME: scheduler

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: default

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short commit hash
        id: vars
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: cr.aops.tools
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64