name: CI

on:
  workflow_dispatch:

env:
  REGISTRY: cr.aops.tools/aops-docker-repo
  IMAGE_NAME: ec2-power-scheduler
  K8S_NAMESPACE: ec2-power-scheduler
  K8S_RESOURCE_TYPE: cronjob
  K8S_RESOURCE_NAME: ec2-power-scheduler
  K8S_CONTAINER_NAME: scheduler

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: cr.aops.tools
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        platforms: linux/amd64

    - name: Make update-deployment.sh executable
      run: chmod +x k8s/update-deployment.sh

    - name: Update Kubernetes resource
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
        k8s/update-deployment.sh ${{ github.sha }}