name: CI Test

on:
  push:
    branches:
      - '**'

jobs:
  ci-test:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest 